### ISSUE TITLE
license of the dataset

### ISSUE THREAD

**Issue by ShogoYamashitaExwzd** [upeee/GOO-GAZE2021#13]
Thank you for sharing this excellent code and the dataset. 
Could you kindly provide us with details about the license?

If we refer to or utilize the code and the dataset, we kindly request information about the license to ensure proper referencing and usage. It will serve as a valuable reference as we progress with our internal R&D projects.

**Comment by roatienza** [comment]
Apache 2.0 License added. Thanks for asking.

**Comment by ShogoYamashitaExwzd** [comment]
Thanks a lot for the quick response.
