### ISSUE TITLE
Hello, how long does it take to train for 1080Ti?

### ISSUE THREAD

**Issue by chenchaoyue1120** [upeee/GOO-GAZE2021#3]
Hello, how long does it take to train for 1080Ti?

**Comment by henritomas** [comment]
Hi Chen!

On GOO-Synth Data, we recommend training using the gaze network used by Chong et. al., which performs the best at a training time of **40 hours** for 25 epochs. This comes around to roughly 1 hr 36 minutes per epoch on the 1080 Ti. 

On GazeFollow Data, the same model by Chong et. al. has a training time of **21 hours** for 50 epochs, around 26 minutes per epoch.
