### ISSUE TITLE
Training steps of the data set.

### ISSUE THREAD

**Issue by chenchaoyue1120** [upeee/GOO-GAZE2021#4]
Hello, I would like to ask about the specific training steps. The description in the readme  is not very clear. I want to reproduce the code. I have downloaded the goosynth_test, goosynth_train and gooreal datasets, but I don't  know how to deal with the images and data folders, how should the path of the dataset be set?

**Comment by remarkSD** [comment]
There is also another readme inside the gazefollowing folder (https://github.com/upeee/GOO-GAZE2021/tree/main/gazefollowing). Details on how to use the GOO dataset for training should be there.
