### ISSUE TITLE
Cannot find trainpickle2to19human.pickle and testpickle120.pickle in the downloaded dataset

### ISSUE THREAD

**Issue by gbymat** [upeee/GOO-GAZE2021#5]
Hello,
The following is the command you provided in the readme, but I cannot find trainpickle2to19human.pickle and testpickle120.pickle in the downloaded dataset.
Can you provide me with some assistance?

Training on GOOSynth:
```
python main.py --baseline='gazenet' \
--train_dir='../goosynth/1person/GazeDatasets/' \
--train_annotation='../goosynth/picklefiles/trainpickle2to19human.pickle' \
--test_dir='../goosynth/test/' \
--test_annotation='../goosynth/picklefiles/testpickle120.pickle' \
--log_file='training.log' \
--save_model_dir='./saved_models/temp/' \

**Comment by henritomas** [comment]
Hi! It seems it was our mistake, not making the following files available in the downloaded dataset. For now, use this link to download the required pickle files:

~~removed old link~~

Please feel free to reply should there be any more additional issues.

**Comment by gbymat** [comment]
The path of train_dir(test_train) should point to which part of the downloaded dataset？ The downloaded dataset contains two parts: images and data.
I get the following error while running the code:
AttributeError: 'NoneType' object has no attribute 'shape'

Thanks.

**Comment by henritomas** [comment]
`train_dir` and `test_dir` should both point to the images directory; Let me know if you encounter further issues.

**Comment by gbymat** [comment]
The ‘filename’ in the testpickle120.pickle and trainpickle2to19human.pickle is different from the parameters in the images folder, which causes the image reading to fail. 
Is there any way to solve it？
For example，
named ’0.png‘ in the images, but ’filename：3-11-0.7-2-8-img1.png‘ in the pickle

**Comment by remarkSD** [comment]
Sorry for the confusion. Apparently we uploaded an older version of the pickle files. Please check the following files:
trainPickleNoSegm: https://drive.google.com/file/d/1kvDAOdglW7ns2Ng3y_q8_hNEBZN6al24/view?usp=sharing
testPickleNoSegm: https://drive.google.com/file/d/1yIaxXO25Y-Mycy2VJ49QqgNYsKIJ8U16/view?usp=sharing

Edit: New links for the dataset are added. Dataset now uploaded to zenodo.
